In [1]:
import numpy as np

In [17]:
# 1D array
a = np.array([1, 2, 3], dtype='float16') # a 1 by 3 array
print(a)

# 2D array
b = np.array([[1, 2, 3], [1, 2, 3]], dtype='float64') # a 2 by 3 array
print(b)

[1. 2. 3.]
[[1. 2. 3.]
 [1. 2. 3.]]


In [18]:
# Get Dimension
print(a.ndim)
print(b.ndim)

# Get Shape
print(a.shape)
print(b.shape)

1
2
(3,)
(2, 3)


In [20]:
# Memory size allocation based on dtype
print(a.nbytes)
print(a.size)
print(a.itemsize)

print(a.size * a.itemsize == a.nbytes)

6
3
2
True


In [43]:
# Manipulating np array
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a.shape)
print(a)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# Get a specific element: [r, c]
print(a[1, 5] == 13)

True


In [38]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [39]:
# Get a specific column
print(a[:, 1])

[2 9]


In [40]:
# Get a specific row range and column range
print(a[:2, :3])

[[ 1  2  3]
 [ 8  9 10]]


In [41]:
# Get a range with step
print(a[0, 1:6:2])

[2 4 6]


In [51]:
# Modifying elements
print(a[:, 1])
a[:, 1] = [10, 11]
print(a)

[ 5 10]
[[ 1 10  3  4  5  6  7]
 [ 8 11 10 11 12 13 14]]


In [58]:
# 1s matric
print(np.ones((4, 2, 2), dtype='int32'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [59]:
# full populate
print(np.full((2, 2), 4))

[[4 4]
 [4 4]]


In [60]:
# Random decimal number between 0-1
np.random.rand(5, 3)

array([[0.24600595, 0.85292626, 0.55261356],
       [0.2248639 , 0.98361299, 0.09752759],
       [0.70578018, 0.18655417, 0.55933502],
       [0.84613502, 0.99186341, 0.08810675],
       [0.48798954, 0.61707013, 0.98418661]])

In [70]:
# Random ints between a specified start:end(exclusive)
np.random.randint(0,10, size=(2, 4))

array([[7, 9, 5, 3],
       [9, 9, 1, 8]])

In [74]:
# Identity matrix
np.identity(4, dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [85]:
# Repeat array
a = np.array([[1, 2, 3]])
a = np.repeat(a, 3, axis=0) #axis 0 specifies a repetition on the rows, while axis 1 specifies on columns (can go to higher d)
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [88]:
# ex
a = np.ones((5, 5), dtype='int8')
a[1:-1, 1:-1] = 0
a[2, 2] = 9

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [92]:
# Deepcopy of array
import copy
b = copy.deepcopy(a)
b[2,2] = 1

print(a)
print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [108]:
# Mathematics
a = np.array([1, 2, 3.14/2])
a = np.sin(a)
print(a)

a = a**2
print(a)

b = np.ones((1, 3))
print(a+b)

[0.84147098 0.90929743 0.99999968]
[0.70807342 0.82682181 0.99999937]
[[1.70807342 1.82682181 1.99999937]]


In [118]:
# Linear Algebra
# Multiplication: valid: mxn * nxq => resulting in matrix of shape mxq
# Matric Multiplcation follows the dot product to populate the matrix (ex: pos(1, 2) => 1st row * 2nd colum))

a = np.random.randint(1,5, size=(2, 3))
print(a)

b = np.random.randint(1,5, size=(3, 4))
print(b)

prod = np.matmul(a, b)
print(prod)

[[1 3 4]
 [2 1 3]]
[[1 1 1 2]
 [1 4 2 3]
 [1 4 3 4]]
[[ 8 29 19 27]
 [ 6 18 13 19]]


In [121]:
# things to refresh on:
# determinant
c = np.identity(3)
print('determinant of identity matrix:', np.linalg.det(c))

# inverse of matrix
# eigenvalues

determinant of identity matrix: 1.0
